### ISSUE TITLE
Create Flutter version of the MDS web site

### ISSUE THREAD

**Issue by Kypsis** [coingaming/moon_flutter#119]
Create Flutter version of the MDS web site mirroring all the functionality both React and Elixir sites have.

**Comment by dickermoshe** [comment]
I would like to create a nice site for this.
Should I modify the example or create a new project?

**Comment by Kypsis** [comment]
Currently we are not taking outside contributions for this issue as this ties very much into our corporate roadmap and priorities.

**Comment by Kypsis** [comment]
We have decided not to proceed with specific web page but will continue using our forked version of storybook as it now handles regular pages to relay miscellaneous information, eg typography, colors etc.
