### ISSUE TITLE
Context menu does no appear in input components

### ISSUE THREAD

**Issue by vital-edu** [coingaming/moon_flutter#410]
## Steps to reproduce

1. Run the example application on a mobile device (iOS or Android)
2. Navigate to the `MoonTextInput`, `MoonTextArea` or `MoonTextInputGroup` component
3. Type some text in the input field (e.g.: "text")
4. Double tap into the text
5. The text is selected

## Expected result

1. Context menu should appear above the input area with options like: Cut, Copy, Look up, etc

## Logs and information

Moon Design **v0.57.0**

```
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.4.1 23E224 darwin-arm64, locale en-EE)
    • Flutter version 3.19.6 on channel stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (7 weeks ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1
```

**Comment by Kypsis** [comment]
Fixed in #417.
