### ISSUE TITLE
feat: `showMoonModalBottomSheet` don't require `animationController`

### ISSUE THREAD

**Issue by dickermoshe** [coingaming/moon_flutter#411]
In the standard material bottom sheet `showModalSheet` doesn't require that a `animationController` is provided.
It would be really awesome if `showMoonModalBottomSheet` didn't require that one be provided

**Comment by Kypsis** [comment]
![Screenshot 2024-06-05 at 13 41 31](https://github.com/coingaming/moon_flutter/assets/46851868/0eb48f49-dac2-4d4c-8aeb-b211a9daf1ed)
 Not sure what do you mean as `animationController` is optional prop.

**Comment by dickermoshe** [comment]
Good point, I got confused with the actual `MoonBottomSheet` iwdget
