### ISSUE TITLE
feat: `onLongTap` and `selected` for `MoonMenuItem`

### ISSUE THREAD

**Issue by dickermoshe** [coingaming/moon_flutter#420]
_Title says it all_

**Comment by Kypsis** [comment]
With v1.0.0 we have frozen all feature work and are focusing on v2.

**Comment by dickermoshe** [comment]
> With v1.0.0 we have frozen all feature work and are focusing on v2.

If v2 won't be including any new features, then what is it for?
Kind of confused what this means regarding the future of this repo?

**Comment by dickermoshe** [comment]
Ah, v2 of the moon spec, gotcha
