### ISSUE TITLE
Usage Documentation

### ISSUE THREAD

**Issue by moha-b** [coingaming/moon_flutter#421]
I have seen the website and it's amazing 🤩 , tbh. I want to use some of these components in my future apps. However, all I found in the readme was just `theme` and more details are needed.

**Comment by Kypsis** [comment]
The current documentation will remain as is since v1 is targeted towards our internal customers. Since v2 is planned with more flexibility and product agnostic approach in mind there is no point to really expand the v1 documentation other than listing the bespoke theming solution.

**Comment by jtkeyva** [comment]
will v2 be MIT? i see you went MIT > GNU > MIT
i would like to commit to this but don't want to be surprised if v2 is GNU
thanks

**Comment by jtkeyva** [comment]
great thanks
