### ISSUE TITLE
Consider change colour names

### ISSUE THREAD

**Issue by JCKodel** [coingaming/moon_flutter#425]
I'm impressed with the widgets so far, but those colour names are a no-no for me =(

Consider using some standard, such, I don't know, maybe red, green, blue... ¬¬

**Comment by Alvish0407** [comment]
They are based on [Dragon Ball Z](https://en.wikipedia.org/wiki/Dragon_Ball_Z) 😁

**Comment by JCKodel** [comment]
> They are based on [Dragon Ball Z](https://en.wikipedia.org/wiki/Dragon_Ball_Z) 😁

Right. So this project is a kid toy.

Gotcha.
