### ISSUE TITLE
Phone input form field with  country picker -  text form field with country picker support.

### ISSUE THREAD

**Issue by shajin-sha** [coingaming/moon_flutter#443]
it would be amazing if we can bring an country picker component (inbuilt)

I know it is possible with adding leading widget to text field & modification may archive same.

Happy to open pull request if allowed or in your roadmap..

**Comment by Kypsis** [comment]
This is something that is not in our design system and is better handled via another package regardless. I understand that the current country flag picker solutions out there all have their shortcomings. But country flag picker is something that has a lot of product specific constraints (served from assets, fetched from flag-cdn, sizes, shapes etc). So currently we are not considering implementing it.
