### ISSUE TITLE
build failed on Example project

### ISSUE THREAD

**Issue by seunghyeoks** [coingaming/moon_flutter#448]
When I was running the example project, I encountered the following error.

> Launching lib/main.dart on iPhone 15 Pro in debug mode...
> Running Xcode build...                                                  
> Xcode build done.                                            5.5s
> Failed to build iOS app
> Error (Xcode): ../../../../../.pub-cache/hosted/pub.dev/win32-4.1.4/lib/src/guid.dart:31:9: Error: Type 'UnmodifiableUint8ListView' not found.
> Could not build the application for the simulator.
> Error launching application on iPhone 15 Pro.

I changed the two packages below to the latest one and the build was successful. Please refer to it.

> \> package_info_plus 8.1.1 (was 3.1.2)
> \> win32 5.8.0 (was 4.1.4)

**Comment by seunghyeoks** [comment]
It seems that the UnmodifiableUint8ListView part has been deprecated in win32.

**Comment by Kypsis** [comment]
This should now be hopefully fixed with latest version.
